# Конфиг дискорд-бота. Для его сброса удалите этот файл или переименуйте, к примеру в config.toml.old
# дабы сохранить информацию
# ©️ 2026 KiKa

# Version - версия бота. Не меняйте значение, если хотите, чтобы при следующем обновлении конфиг сам обновился
# Token - ваш токен бота. Взять можно тут - https://discord.com/developers/applications
  # Выглядит примерно как g3MTQxcxMTxNDI3Mg.GhAjfo.hqSZPff72zw5QSffd
# Prefix - префиксы от которых работает бот.
# Если указать пустоту, бот будет отвечать на команды без префикса
# Это бы выглядело примерно как prefix = (["", "!"]
[main]
version = "${version}"
token = "ТОКЕН" # Обязательно
prefix = ["!", ".", "?"]

# Host - хост, куда подключаться к базе данных
  # Дефолтно localhost. Обычно вы подключаетесь не удаленно к базе данных
# Port - порт базы данных
  # Дефолтно 5432. Этот порт выбирается автоматически при установке базы данных PostgreSQL
# Name - название базы данных
# User - имя пользователя, от кого подключаться к базе данных
  # Дефолтно postgres. У него есть доступ ко всем базам данных
# Password - пароль от пользователя
[database]
host = "localhost"
port = 5432
name = "name" # Обязательно
user = "postgres"
password = "password" # Обязательно

[economy]
# Дефолтный выигрыш с фермы от 5 до 50
min = 5
max = 50
# Дефолтный минимальный джекпот от 200 до 500
min_mini = 200
max_mini = 500
# Дефолтный максимальный джекпот от 1000 до 2000
min_large = 1000
max_large = 2000
# Дефолтный проигрыш от -50 до -1
min_loss = -1
max_loss = -50

# Шансы пишутся в процентах от 100.0 до 0.0
# Обязательно число должно быть типа double, то есть с плавающей точкой. Пример: 0.0
#                                                                        Так: 0 <--- НЕ правильно
[economy.chances]
# Шанс потерять коины 0.1%
loss_reward = 0.1
# Шанс на минимальный джекпот 5%
mini_reward = 5.0
# Шанс на крупный джекпот 0.5%
large_reward = 0.5